### ISSUE TITLE
Add a task for composer self-updater

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/ansible-role-composer#11]
Let me know if this doesn't interest you, but composer doesn't appear to be updating like ever...
If you don't, I'll make up a little one myself but this is something everybody could be using.

Could you add a variable similar to that of drush such as `keep_composer_updated` and associate a task to run `composer self-update` as the root user?

**Comment by geerlingguy** [comment]
This already exists... https://github.com/geerlingguy/ansible-role-composer/blob/master/tasks/main.yml#L25-L30

If you set `composer_keep_updated` to `true` in your playbook, it will update composer every time the role is run.

**Comment by fubarhouse** [comment]
Lol, my bad... Thanks, and sorry.

**Comment by geerlingguy** [comment]
No problem!
