### ISSUE TITLE
Different php executable causes Composer to fail

### ISSUE THREAD

**Issue by opdavies** [geerlingguy/ansible-role-composer#13]
I've installed PHP 5.5 using the `geerlingguy.repo-remi` and `geerlingguy.php` roles, which has resulted in my PHP executable being `php55` rather than just `php`. Because of this, the tasks in this role fail because it's looking only for the `php` executable.

My original thought was to add a symlink, maybe in a custom role, or either make the executable configurable in this role, or inherit the default from `geerlingguy.php`, but I was interested on your thoughts @geerlingguy before I proceed with either option.

Here is my PHP role configuration:

```
php_enablerepo: remi
php_packages:
  - php55-php
  - php55-php-cli
  - php55-php-common
  - php55-php-gd
  - php55-php-mbstring
  - php55-php-pdo
  - php55-php-pear
  - php55-php-pecl-apc
  - php55-php-xml
  - php55-php-xmlrpc
php_conf_path: /opt/remi/php55/root/etc
php_webserver_daemon: httpd
php_date_timezone: "Europe/London"
```

**Comment by geerlingguy** [comment]
The latest version of the `geerlingguy.php` role uses `php_executable` to define the executable (or full path) to use. You could override that, setting it to `php55`, then we could update this role to use that instead of just `php`...

**Comment by opdavies** [comment]
Awesome! :+1:

**Comment by geerlingguy** [comment]
I'll be tagging it in 1.2.5 and pushing to Galaxy in a few minutes after tests pass.
