### ISSUE TITLE
Composer uses git, and git is not installed in this role

### ISSUE THREAD

**Issue by tchaffee** [geerlingguy/ansible-role-composer#15]
Since composer will sometimes use git, would it be possible to add the following to this role?

```
- name: install git
  apt: name=git state=present
```

**Comment by geerlingguy** [comment]
@tchaffee - I'd rather just document that Git is a soft requirement, and if someone needs to make sure it's installed, they should add the `geerlingguy.git` role prior to this role.

**Comment by tchaffee** [comment]
That works. Thanks.
