### ISSUE TITLE
Default composer_home_owner as ansible_ssh_user

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/ansible-role-composer#17]
There are a few issues with this:
- We can't really use `become` as the path might not be writable by the user
- If we use `file` modules chown ability the default path of `~/.composer` would become `/root/.composer`
- Using `/home/{{ composer_home_owner }}` isnt really reliable in the case of root or osx.
- If we use `file` modules chown ability we do not know the users primary group (on unix we can assume it's the same as the users name but someone might run this on osx too)

So we either:

1. Remove the default variable values and use two `shell` commands to figure out `$HOME` as well as `$GROUP` and then set them as facts if not previously defined.
2. We use `become` and do not support paths which are not writable by the user

**Comment by geerlingguy** [comment]
Hmm... Another option is to just explicitly add the defaults in Drupal VM and other upstream projects in config.yml.

**Comment by oxyc** [comment]
Sounds like a good option. I created a PR for it if you prefer doing that.

**Comment by geerlingguy** [comment]
I like it; closing this as a 'wontfix'
