### ISSUE TITLE
Consider removing annoying logic/vars that supported the GitHub OAuth token

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-composer#19]
Basically we may be able to scrap `composer_github_oauth_token` and it's functionality, as it looks like the rate limits have been lifted upstream by GitHub, partly due to some prodding by the Composer and Drupal projects: https://github.com/composer/composer/issues/4884#issuecomment-195229989

**Comment by wells** [comment]
I'm pretty certain that this is still a useful feature to retain in this role when using the hirak/prestissimo plugin for parallel installs from GitHub.

**Comment by geerlingguy** [comment]
Closing this out for now—it is valuable in many situations, and no use removing a nicely-working feature.
