### ISSUE TITLE
Add configuration directive to globally require packages

### ISSUE THREAD

**Issue by phenaproxima** [geerlingguy/ansible-role-composer#2]
It would be awesome if I could use this role to automatically install a suite of packages globally. Something like:

```
composer_global_packages:
  - 'phpunit/phpunit'
  - 'behat/behat'
  - 'symfony/validation'
```

If this is easy to add, I humbly request it. :)

**Comment by geerlingguy** [comment]
Yes, this would be simple enough to add, and would be convenient for a number of people :)

**Comment by geerlingguy** [comment]
Finally had a little time (and impetus: https://github.com/geerlingguy/drupal-vm/issues/124) to get this done.
