### ISSUE TITLE
--no-interaction mode

### ISSUE THREAD

**Issue by TheHett** [geerlingguy/ansible-role-composer#20]
Hello,
could you add `--no-interaction` option ?

**Comment by geerlingguy** [comment]
Do you mean in reference to the global package installs, e.g. https://github.com/geerlingguy/ansible-role-composer/blob/master/tasks/global-require.yml ?

**Comment by TheHett** [comment]
@geerlingguy 

https://getcomposer.org/doc/03-cli.md
```
--no-interaction (-n): Do not ask any interactive question.
```
