### ISSUE TITLE
drupal/drupal-extension started failing due to mink dependency

### ISSUE THREAD

**Issue by michaelpporter** [geerlingguy/ansible-role-composer#21]
This morning while running Drupal-VM - vagrant provision I started getting an error on "drupal/drupal-extension". 
- { name: drupal/drupal-extension, release: '*' }

The raw out put is in at https://gist.github.com/michaelpporter/2656f9f0990f16e05f06

There is also a deprecation warning.

[DEPRECATION WARNING]: Using bare variables is deprecated. Update your
playbooks so that the environment value uses the full variable syntax
('{{composer_global_packages}}'). This feature will be removed in a future
release. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.

**Comment by geerlingguy** [comment]
From that gist, it looks like this is the issue:

```
drupal/drupal-extension v0.1.1 requires behat/mink 1.4@stable -> no matching package found.
```

You're installing 1.5—either need to adjust the composer.json requirements (can you post your file?), or drupal-extension will need to be updated itself so it's latest release works with the latest mink release.

**Comment by geerlingguy** [comment]
Also fixed the deprecation warning (see above commit) in Ansible 2.x.

**Comment by michaelpporter** [comment]
composer_global_packages:
  - { name: behat/mink, release: '1.5.*@stable' }
  - { name: behat/mink-goutte-driver, release: '*' }
  - { name: behat/mink-selenium2-driver, release: '*' }
  - { name: drupal/drupal-extension, release: '~3.0' }

I will change it to 1.4 and test

**Comment by michaelpporter** [comment]
FYI I got the list form DrupalVM docs/extras/behat.md

**Comment by geerlingguy** [comment]
@michaelpporter - In that case, can you open an issue in the drupal-vm repo and I'll add the 'docs' tag to it, since that might be the best way to fix this issue. I don't think the issue can be resolved through any changes to this particular role.
