### ISSUE TITLE
Download/Install fails with SSL-Error

### ISSUE THREAD

**Issue by derheap** [geerlingguy/ansible-role-composer#22]
If for some reason the package `ca-certificates` is not present on Debian Linux, the download or install of Composer fails with an SSL error.

It took me awhile to get to the main problem.

This fixes the problem:

```
- name: Add certs
  apt: name="ca-certificates" state="present"
```

**Comment by jiv-e** [comment]
We had a same kind of problem with Centos when using proxy behind firewall.

`fatal: [193.167.238.24]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for www.kernel.org:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}`

Only fix we found was add `validate_certs=False` to /tasks/install-from-source.yml's task "Download Composer installer".

Is there any other way fix this without editing the role? If not, would it be possible to add variable switch for validate_certs?

This problem also occurred with https://github.com/geerlingguy/ansible-role-git.

**Comment by geerlingguy** [comment]
@jiv-e - Just installing the `ca-certificates` doesn't help? It sounds like the firewall/proxy might be MITM'ing all the SSL traffic in that case... and that's something that I kinda despise :P
