### ISSUE TITLE
"/bin/sh: composer: command not found"

### ISSUE THREAD

**Issue by ados1991** [geerlingguy/ansible-role-composer#23]
TASK [ansible-role-composer-master : Set php_executable variable to a default if not defined.] ***
skipping: [stackradio.local] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [ansible-role-composer-master : Check if Composer is installed.] **********
ok: [stackradio.local] => {"changed": false, "stat": {"atime": 1462394386.143436, "checksum": "8cb414603614c033528c6988b03f98a1d834f5f4", "ctime": 1462394104.0745864, "dev": 64768, "exists": true, "gid": 0, "gr_name": "root", "inode": 51484252, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "md5": "992f9395613c9ed60c963181555ab77d", "mode": "0755", "mtime": 1462394101.1302123, "nlink": 1, "path": "/usr/local/bin/composer", "pw_name": "root", "rgrp": true, "roth": true, "rusr": true, "size": 1592154, "uid": 0, "wgrp": false, "woth": false, "wusr": true, "xgrp": true, "xoth": true, "xusr": true}}

TASK [ansible-role-composer-master : Download Composer installer.] *************
skipping: [stackradio.local] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [ansible-role-composer-master : Run Composer installer.] ******************
skipping: [stackradio.local] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [ansible-role-composer-master : Move Composer into globally-accessible location.] ***
skipping: [stackradio.local] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [ansible-role-composer-master : Update Composer to latest version (if configured).] ***
skipping: [stackradio.local] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [ansible-role-composer-master : Ensure composer directory exists.] ********
ok: [stackradio.local] => {"changed": false, "gid": 0, "group": "root", "mode": "0755", "owner": "root", "path": "/root/.composer", "size": 45, "state": "directory", "uid": 0}

TASK [ansible-role-composer-master : Add GitHub OAuth token for Composer (if configured).] ***
skipping: [stackradio.local] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [ansible-role-composer-master : Install configured globally-required packages.] ***
failed: [stackradio.local] (item={u'release': u'^3.0', u'name': u'slim/slim'}) => {"changed": true, "cmd": "COMPOSER_HOME=~/.composer composer global require slim/slim:^3.0 --no-progress", "delta": "0:00:00.008793", "end": "2016-05-04 22:05:09.008222", "failed": true, "item": {"name": "slim/slim", "release": "^3.0"}, "rc": 127, "start": "2016-05-04 22:05:08.999429", "stderr": "/bin/sh: composer: command not found", "stdout": "", "stdout_lines": [], "warnings": []}
        to retry, use: --limit @dev.retry

I am on centos7, i have this issue which is impossible for composer to install packages.
But when i am on local machine console, composer is installed and even i can install packages manually. 

[root@stackradio vagrant]# /bin/sh
sh-4.2# composer
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 1.0.3 2016-04-29 16:30:15

Usage:
  command [options] [arguments]

Solution ?

**Comment by geerlingguy** [comment]
`ansible-role-composer-master` --> I'm guessing you cloned the role straight from GitHub and didn't install using Ansible Galaxy? If so, can you make sure you're on the latest version of the code or the latest tag?

What user are you using for your playbook? If you login as that user, and run `which composer`, does it give you the full path to composer?

**Comment by JorisVanEijden** [comment]
I have the same issue.
composer is installed in `/usr/local/bin/` which is not in the root users path by default on CentOS 6.
I created a PR to use the {{ composer_path }}

**Comment by ados1991** [comment]
yes i fix it with {{ composer_path }} instead of composer in 
shell: >
    COMPOSER_HOME={{ composer_home_path }}
    composer global require {{ item.name }}:{{ item.release | default('@stable') }} --no-progress
    creates={{ composer_home_path }}/vendor/{{ item.name }}
