### ISSUE TITLE
ansible-lint complains about global-require.yml

### ISSUE THREAD

**Issue by bbaassssiiee** [geerlingguy/ansible-role-composer#29]
[ANSIBLE0014] Environment variables don't work as part of command
/m/ansible/roles/geerlingguy.composer/tasks/global-require.yml:2
Task/Handler: Install configured globally-required packages.

[ANSIBLE0013] Use shell only when shell functionality is required
/m/ansible/roles/geerlingguy.composer/tasks/global-require.yml:2
Task/Handler: Install configured globally-required packages.

**Comment by B-Galati** [comment]
As per the commit message, this issue should be closed no ?

**Comment by geerlingguy** [comment]
Yep!
