### ISSUE TITLE
Optionally add COMPOSER_HOME/vendor/bin to global $PATH

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-composer#3]
Adding the following inside `/etc/profile.d/composer.sh` will add the `COMPOSER_HOME/vendor/bin` path to all users' PATHs on the system. This should make setup for `global require`'d packages simpler, so the user doesn't have to do the path modification himself.

**Comment by aaronbauman** [comment]
This seems to be working for an interactive login, but the new $PATH variable isn't available to my other ansible tasks. They're still seeing only the value from /etc/environment since the ansible shell is not interactive.

How do I get ansible to make this available to other tasks?
