### ISSUE TITLE
Vagrant up is causing "Failed to download the file"

### ISSUE THREAD

**Issue by gtso86** [geerlingguy/ansible-role-composer#45]
I'm trying to install Trellis on my computer after runs vagrant up I get this error:

```
default: Running ansible-galaxy...
- downloading role 'composer', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-composer/archive/1.6.1.tar.gz
 [ERROR]: failed to download the file: Failed to validate the SSL certificate
for github.com:443. Make sure your managed systems have a valid CA certificate
installed. You can use validate_certs=False if you do not need to confirm the
servers identity but this is unsafe and not recommended. Paths checked for this
platform: /etc/ssl/certs, /etc/ansible, /usr/local/etc/openssl

 [WARNING]: - composer was NOT installed successfully.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Searching about this problem I found [this](https://discourse.roots.io/t/can-not-provision-properly-local-server-setup/8319/2) and [this](https://github.com/ansible/ansible/issues/18446) topic but none have a workaround to fix it. Any idea what is causing the problem?

**Comment by rangiTM** [comment]
Same error here, Ubuntu + Trellis

**Comment by gtso86** [comment]
The problem isn't related with Ansible role composer... I fixed updating my Python + openSLL. I followed these instructions [here](https://discourse.roots.io/t/vagrant-up-returns-failed-to-download-the-file/11780/2).
