### ISSUE TITLE
Composer Installer Fails

### ISSUE THREAD

**Issue by tschirmer** [geerlingguy/ansible-role-composer#47]
Env:
 - CentOS Linux release 7.5.1804 (Core)
 - Ansible 2.6.1

More info:
 - Run on startup of initial centos image. Problem does not occur when run manually outside of a deployment.

TASK [geerlingguy.composer : Run Composer installer.] **************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["php", "composer-installer.php"], "delta": "0:00:00.024589", "end": "2018-07-26 00:34:06.510243", "msg": "non-zero return code", "rc": 1, "start": "2018-07-26 00:34:06.485654", "stderr": "", "stderr_lines": [], "stdout": "All settings correct for using Composer\nThe HOME or COMPOSER_HOME environment variable must be set for composer to run correctly", "stdout_lines": ["All settings correct for using Composer", "The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly"]}

**Comment by tschirmer** [comment]
The plan I'm testing with is isolated.
`---
- hosts: localhost
   tasks:
     - name: Setup Composer
           include_role:
              name: geerlingguy.composer`

**Comment by psoots** [comment]
I've run into this error when php isn't yet installed.

**Comment by geerlingguy** [comment]
@tschirmer - In whatever environment you're using is there no `$HOME` set? Can you log into that server/container/VM and run `echo $HOME` and see what it gives you? IIRC, Composer _does_ require that one of those two environment variables is set... and on every system I've ever used, at least `$HOME` is set to the current user's home directory (e.g. `/root` for root user, `/home/[username]` for most any other user).

Or maybe you're running this role as a user who doesn't have a home directory? In that case you'll need to make sure `COMPOSER_HOME` is set so Composer knows where to install.

Closing the issue as I think the error message encapsulates the problem, and it seems like if there's any further issue with home/env vars, it might be a bug upstream.
