### ISSUE TITLE
Store Github OAuth token

### ISSUE THREAD

**Issue by sagikazarmark** [geerlingguy/ansible-role-composer#5]
I saw in one of the composer roles the possibility to store github oauth token, so that if composer installation is part of your set up/provision, it won't fail because of Github API Rate limit.

**Comment by geerlingguy** [comment]
I'd rather not add that overhead in this role. It's generally not an issue in most cases—I used to see the rate limit error fairly often, but in the past few months, even when building multiple local VMs in short succession, I haven't run into the error.

I'd still entertain the idea if it's causing a lot of grief, but the complaints about the rate limit error have died down a lot.

**Comment by hcpss-banderson** [comment]
FWIW, I am running into a rate error issue. This feature would be nice, because there is no workaround.
