### ISSUE TITLE
SHA384 is not supported by your openssl extension

### ISSUE THREAD

**Issue by llbbl** [geerlingguy/ansible-role-composer#52]
```
FAILED! => {"changed": true, "cmd": ["php", "/usr/local/bin/composer", "self-update"], "delta": "0:00:01.609223", "end": "2018-11-05 20:28:16.092391", "msg": "non-zero return code", "rc": 1, "start": "2018-11-05 20:28:14.483168", "stderr": "   Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%)         \b\b\b\b\b\b\b\b\b\n\n                                                                                               \n  [RuntimeException]                                                                           \n  SHA384 is not supported by your openssl extension, could not verify the phar file integrity  \n
```

```
ansible-galaxy install geerlingguy.composer,1.7.3 -p roles/ --force
```

Issue exists on composer side. Not sure how to fix. 

https://github.com/composer/composer/pull/7649

**Comment by llbbl** [comment]
Looks like reinstalling works. 

```
sudo rm -f /usr/local/bin/composer
```

**Comment by llbbl** [comment]
Have to delete it and reinstall looks like the official solution. 

https://github.com/composer/composer/issues/7769

**Comment by llbbl** [comment]
We will have to check version number of composer, remove older versions, the install latest, otherwise self update will work on 1.7.3

**Comment by geerlingguy** [comment]
@llbbl - Is this something that could be solved by a change to this role? Or did you solve the solution by just deleting an old Composer version and reinstalling?

**Comment by llbbl** [comment]
@geerlingguy I solved manually because, reasons, by deleting and reinstalling. Yes I think a change would solve this for other people. We would have to add some conditional logic to handle the older versions. 

This would do it but we could only check one version at a time starting from 1.0 release

```
command: composer --version
register: composer_version
changed_when: "'Composer version 1.5.6' in composer_version.stdout"
``` 

Not sure how else to check for less than a specific version number, any ideas on that ? maybe some tcl regexp to pull version out of the version check stdout ?

**Comment by tersmitten** [comment]
Ansible commands (I used) for reinstall:

```sh
ansible all -i inventory.py -m file -a 'path=/usr/local/bin/composer state=absent';
ansible-playbook -i inventory.py common-build.yml --tags composer;
```

**Comment by geerlingguy** [comment]
I think the solution of 'if you get this error, delete and then run the role/playbook again' is going to be the best option. I don't want to add a shim in the role to try to detect certain older versions and have a delete/reinstall loop in there just for that case.

**Comment by samadesina** [comment]
hello pls I am still having this error, I am using the latest version of xampp and composer but still getting "SHA384 is not supported by your openssl extension" when I try installing composer 
![response](https://user-images.githubusercontent.com/47450494/53390852-e4ea1580-3994-11e9-9aa1-2331f3139ddc.JPG) kindly help me with solution thanks

**Comment by marthad-musa** [comment]
Hey Guys, I'm having a different kind of problem. I just bought a new laptop and this problem appeared while installing composer. An error message saying: "SHA384 is not supported by your openssl extension composer". Anytime  I try to reinstall the software I get the same error message and there are no older version installed to remove. So, other than reinstalling, is there any other solution?

**Comment by llbbl** [comment]
@marthad-musa you have to find where composer is installed and delete it either manually or by passing ansible command. Many people just use Homebrew "brew" to manage their composer locally.
