### ISSUE TITLE
composer_version not honored when a previous version is installed

### ISSUE THREAD

**Issue by EmilioMoreno** [geerlingguy/ansible-role-composer#63]
if you specify a version using "composer_version" variable and composer is not installed previously, everything works ok, but if you want to upgrade/downgrade later on to a different composer version,  and composer is already installed (no matter what version),  the role finishes without doing anything but composer is not upgraded/downgraded.

As we work on specific versions of composer and upgrade to specific versions and not always to the latest, this role do not allow us to upgrade composer.

**Comment by versusbassz** [comment]
I'm not an experienced ansible developer ofc, but i think this behavior isn't correct. Updating composer phar file via changing the role's var could be very very convenient.

**Comment by ngstigator** [comment]
> I'm not an experienced ansible developer ofc, but i think this behavior isn't correct. Updating composer phar file via changing the role's var could be very very convenient.

if you use the `composer_version_branch` option you can at least change to version 1 i.e. 1.10.17
e.g. `composer_version_branch: '--1'`

note that `composer_version` is ignored, so you will not be able install a specific version.

hope this helps.

**Comment by gdubicki** [comment]
See also #72 and #77 as they are related.
