### ISSUE TITLE
composer_version isn't respected

### ISSUE THREAD

**Issue by loceee** [geerlingguy/ansible-role-composer#72]
Howdy.

since composer_version_branch is defaulted: 
https://github.com/geerlingguy/ansible-role-composer/blob/master/defaults/main.yml#L5

composer_version never gets tested for here..
https://github.com/geerlingguy/ansible-role-composer/blob/master/tasks/main.yml#L28

Thanks for the great roles and books!

**Comment by gdubicki** [comment]
Can we please reopen this?

I just got hit by this as the module installed composer 2.3.* in place of 2.1.* that I expected and that version of composer was not backward compatible and caused an issue.

My config was:
```
# latest 2.1.x version as of now
composer_keep_updated: true
composer_version: '2.1.12'
composer_version_branch: '--2'
```

I think that if you set `composer_version` along with `composer_keep_updated` or `composer_version_branch` the module should fail with a "contradicting parameters" error.
